ws/conf/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path("recipes/", include("core.urls")),
    path("admin/", admin.site.urls),
]

ws/core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = "core"
urlpatterns = [
    path("", views.home, name="home"),
    path("rescan/", views.rescan, name="rescan"),
    path("search/", views.search, name="search"),
    path("items/", views.items, name="items"),
    path("item/", views.item, name="item"),
    path("item/delete/", views.delete, name="item_delete"),
    path("tags/", views.tags, name="tags"),
    path("login/", auth_views.LoginView.as_view()),
]

ws/core/models.py
import frontmatter

from django.db import models
from django.utils import timezone

# Create your models here.


class Tag(models.Model):
    """A string that can be attached to an item.

    Attributes
    ----------
    name : str
        The name of the tag

    """

    name = models.CharField(max_length=100)

class Item(models.Model):
    """The markdown item

    Attributes
    ----------

    title : str
        The title in the markdown file

    created : datetime
        When created (can be specified in head of markdown)

    accessed: datetime
        Last accessed

    tags: 
        A many to many relationship with tags

    content:

    path:
        Path to file on disk that this item represents

    """

    title = models.CharField(max_length=100)
    created = models.DateTimeField()
    accessed = models.DateTimeField(blank=True, null=True)
    tags = models.ManyToManyField(Tag)
    path = models.CharField(max_length=200)

    @classmethod
    def create(cls, filename):
        """Return a new Item

        Parameters
        ----------
        filename : str
            The full path of markdown file

        Returns
        -------
        Item
            The new Item
        """

        with open(filename) as f:
            text = frontmatter.load(f)

        if 'title' not in text:
            raise ValueError(f"No title in {filename}")
            
        item = cls(
            title=text['title'],
            path=filename
        )

        if 'date' in text:
            item.created = text['date']
        if 'accessed' in text:
            item.accessed = text['accessed']

        tags = []
        if 'tags' in text:
            tags = [
                Tag.objects.get_or_create(name=tag)[0]
                for tag in text['tags'].split()
            ]

        return (item, tags)

ws/core/views.py
import os
import re
import markdown
import frontmatter
import json
from pathlib import Path

from django.shortcuts import render
from django.conf import settings
from django.utils.safestring import mark_safe
from django.utils import timezone
from django.views.decorators.http import require_http_methods
from django.http import JsonResponse

from django.contrib.auth.decorators import login_required


from .models import Item, Tag


@login_required(login_url="/recipes/login/")
def home(request, msg=None):
    """Home view

    Parameters
    ----------
    request: django.http.request

    msg: str
        A mark_safed string to display in the main
    """

    return render(
        request,
        "core/items.html",
        {
            "tags": Tag.objects.all().order_by("name").values_list("name", flat=True),
            "msg": msg,
        },
    )


@login_required(login_url="/recipes/login/")
def rescan(request):
    """Scan the document repo."""

    # start afresh
    Item.objects.all().delete()
    Tag.objects.all().delete()

    # warning messages
    msg = []

    for path in Path(settings.DOC_REPO).rglob("*.md"):
        try:
            it, tags = Item.create(path)
            it.save()
            it.tags.add(*tags)
        except Exception as exp:
            msg.append(str(exp))

    return home(request, msg=mark_safe("<br />".join(msg)))


@login_required(login_url="/recipes/login/")
@require_http_methods(["GET"])
def search(request):
    """Search for items containing text.

    Parameters
    ----------
    request : django.http.request
        request['tag'] is a tag name, restrict search to this tag
        request['lookfor'] string to look for

    Returns
    -------
    JsonResponse
        {
            'success': bool
            'items': list [(id, title, context), (id, title, context) ...]
            'msg': str
        }
        The msg is only there if there was a problem

        If tag is 'Recipes' then search in all items.

    """

    txt, tag = request.GET["lookfor"], request.GET.get("tag", None)

    if tag and tag not in ("Recipes", "recent"):
        its = Item.objects.filter(tags__name=tag).order_by("title")
    else:
        its = Item.objects.all().order_by("title")

    items = []
    for it in its:
        found = None

        # found refers to Item, and if we found txt in the body context gives
        # us the string where it was found

        if re.search(txt, it.title, re.IGNORECASE):
            found, context = it, None
        else:
            with open(it.path, "r") as handle:
                body = frontmatter.load(handle).content
                m = re.search(txt, body, re.IGNORECASE)
                if m:
                    found = it
                    context = (
                        f"...{body[max(m.start()-20, 0):min(m.end()+20, len(body))]}..."
                        ""
                    )

        if found:
            items.append([it.id, it.title, context])

    return JsonResponse({"success": True, "items": json.dumps(items)})


@login_required(login_url="/recipes/login/")
@require_http_methods(["GET"])
def items(request):
    """Returns items in given tag

    Parameters
    ----------
    request : django.http.request
        request['tag'] is a tag name, or 'recent'

    Returns
    -------
    JsonResponse
        {
            'success': bool
            'items': list [(id, title), (id, title) ...]
            'msg': str
        }
        The msg is only there if there was a problem

        If tag is 'Recipes' then all items returned.  If tag is 'recent'
        return all items sorted by 'accessed'.

    """

    tag = request.GET["tag"]

    if tag == "Recipes":
        its = Item.objects.all().order_by("title")
    elif tag == "recent":
        # not None means never accessed has key = (False, None), and False goes
        # first.  Then we reverse if
        its = sorted(
            Item.objects.all(),
            key=lambda ob: (ob.accessed is not None, ob.accessed),
            reverse=True,
        )
    else:
        its = Item.objects.filter(tags__name=tag).order_by("title")

    return JsonResponse(
        {"success": True, "items": json.dumps([(it.id, it.title) for it in its])}
    )


@login_required(login_url="/recipes/login/")
@require_http_methods(["GET"])
def tags(request):
    """The tags

    Parameters
    ----------
    request : django.http.request

    Returns
    -------
    JsonResponse
        {
            'success': bool
            'tags': dict (id to name)
            'msg': str
        }
        The msg is only there if there was a problem

    """

    tags = {t.id: t.name for t in Tag.objects.all().order_by("name")}

    return JsonResponse({"success": True, "tags": json.dumps(tags)})


@login_required(login_url="/recipes/login/")
@require_http_methods(["GET"])
def item(request):
    """An item

    Parameters
    ----------
    request : django.http.request
        request['id'] is an item ID

    Returns
    -------
    JsonResponse
        {
            'success': bool
            'title': str
            'created': str (YYYY-MM-DD HH:MM:SS) or None
            'last': str either YYYY-MM-DD HH:MM:SS or 'never'
            'tags': list of tag names
            'filename': str
            'content': html str
            'msg': str
        }
        The msg is only there if there was a problem

    """

    try:
        it = Item.objects.get(pk=json.loads(request.GET["id"]))
    except Exception as exp:  # pylint: disable=broad-except
        return JsonResponse({"success": False, "msg": str(exp)})

    tags = [t.name for t in it.tags.all()]
    timezone.localtime(it.created).strftime("%Y-%m-%d %H:%M") if it.created else None
    last = (
        timezone.localtime(it.accessed).strftime("%Y-%m-%d %H:%M")
        if it.accessed
        else "never"
    )

    # get the content
    with open(it.path, "r", encoding="utf-8") as fh:
        text = frontmatter.load(fh)
        content = markdown.markdown(text.content, extensions=["tables"])

    # save back with correct accessed
    with open(it.path, "w", encoding="utf-8") as fh:
        text["accessed"] = it.accessed = timezone.now()
        fh.write(frontmatter.dumps(text))
        it.save()

    return JsonResponse(
        {
            "success": True,
            "title": it.title,
            "created": timezone.localtime(it.created).strftime("%Y-%m-%d %H:%M")
            if it.created
            else None,
            "last": last,
            "tags": json.dumps(tags),
            "filename": os.path.basename(it.path),
            "content": content,
        }
    )


@login_required(login_url="/recipes/login/")
@require_http_methods(["GET"])
def delete(request):
    """Delete an item

    Parameters
    ----------
    request : django.http.request
        request['id'] is an item ID

    Returns
    -------
    JsonResponse
        {
            'success': bool
            'msg': str
        }
        The msg is only there if there was a problem

    """

    try:
        it = Item.objects.get(pk=json.loads(request.GET["id"]))
        os.unlink(it.path)
        it.delete()
    except Exception as exp:  # pylint: disable=broad-except
        return JsonResponse({"success": False, "msg": str(exp)})

    return JsonResponse(
        {
            "success": True,
        }
    )

ws/core/templates/core/base.html
<!doctype html>
<html lang="en">

  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">


    <title>Recipes</title>
  </head>

    <body>

		<div class="container-fluid d-flex flex-column flex-grow-1 overflow-auto">

            <!-- TOP -->

            <nav class="navbar navbar-expand-md navbar-light bg-light">
                <a class="navbar-brand taglink" href="#">Recipes</a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">

                        <li class="nav-item active">
                            <a href="#" class="nav-link taglink">recent</a>
                        </li>
                  
                        {% for tag in tags %}
                            <li class="nav-item active">
                                <a href="#" class="nav-link taglink">{{ tag }}</a>
                            </li>
                        {% endfor %}

                    </ul>

                    <ul class="navbar-nav">

                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'core:rescan' %}">Rescan</a>
                        </li>

                        <input id="search-lookfor" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" id="search-button">Search</button>

                    </ul>
                </div>
            </nav>


			<!-- MAIN -->
			<div class="row flex-grow-1 overflow-auto">

                <div id="sidebar" class="col-sm-3 mh-100 overflow-auto py-2">
                    {% block side %}
                    SIDE
                    {% endblock %}
                </div>

                <div id="main" class='col-sm-9'>
                    {% block content %}
                    MAIN
                    {% endblock %}
			    </div>

            </div>

        </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>


    {% block javascript %}{% endblock %}
  </body>
</html>

ws/core/templates/core/items.html
{% extends 'core/base.html' %}


{% block side %}
    <div id="sidebar-content"></div>
{% endblock %}

{% block content %}
    <div id="msg">
        {% if msg %} {{ msg }} {% endif %}
    </div>

    <div id="itemdisplay" class="container container-fluid">

        <button id="showside" type="button" class="btn btn-sm">
            ❮
        </button>

        <div class="d-flex">
            <div class=""><h2 id="title" style="display:inline;"></h2></div>
            <div class=""><ul id="tags" style="display:inline;"></ul></div>
            <div class="ml-auto"><button id="del-button" type="button" class="btn btn-danger">Delete</button></div>
        </div>

        <table class="table table-sm" style="font-size: 10px;width: auto !important;">
            <tbody>
                <tr style="border-top: none;">
                    <td style="border-top: none;"><i>Created:</td><td style="border-top: none;" id="created"></td>
                </tr>
                <tr style="border-top: none;">
                    <td style="border-top: none;"><i>Last access:</td><td style="border-top: none;" id="last"></td>
                </tr>
                <tr style="border-top: none;">
                    <td style="border-top: none;"><i>Filename:</td><td style="border-top: none;" id="filename"></td>
                </tr>
            </tbody>
        </table>

        <div id="itemout"></div>
    </div>

{% endblock %}

{% block javascript %}

<script>
$(document).ready(function() {


    var current_item = null;
    var current_tag = null;

    // If on big screen we need vh-100 so we get scrollbar in the
    // sidebar, but on small screens we don't want it otherwise the
    // navbar doesn't push content down properly.
    // This doesn't handle it when user resizing window.  They will
    // have to refresh.
    if ( window.matchMedia("screen and (min-width:768px)").matches ) {
        $('div.flex-column').addClass('vh-100');
    }

    // Start off with this hidden because messages maybe displayed in the main window
    // On first item display it will be show()ed.
    $('#itemdisplay').hide();

    // get all the tags
    const tags = function() {
        var tmp = null;
        $.ajax({
            url: "{% url 'core:tags' %}",
            dataType: 'json',
            async: false,
            success: function (data) {
                if (data.success) {
                    tmp = JSON.parse(data.tags);
                } else {
                    alert("Couldn't get tags\nMessage was: " + data.msg);
                }
            }
        });
        return tmp;
    }();

    // If on extra small show side (with col-12) and hide main
    function show_side_hide_main() {
        $('#sidebar').removeClass('d-none d-sm-block').addClass('d-block col-12');
        $('#main').removeClass('d-block col-12').addClass('d-none d-sm-block');
    }
    // If on extra small hide side and show main
    function hide_side_show_main() {
        $('#sidebar').removeClass('d-block col-12').addClass('d-none d-sm-block');
        $('#main').removeClass('d-none d-sm-block').addClass('d-block col-12');
    }
    $('#showside').click(show_side_hide_main);      // button to show the side

    
    // Display an item
    function display_item(e) {
        // e is event of clicking on an item
        const itemid = e.target.id
        $.ajax({
            url: "{% url 'core:item' %}",
            data: {
                'id': itemid
            },
            dataType: 'json',
            success: function (data) {
                if (data.success) {
                    $("#title").html(data.title);

                    $("#tags").empty();
                    JSON.parse(data.tags).sort().forEach(t => {
                        var ta = $("<li style='display:inline;'><a href='#' class='taglink'>" + t + "</a>&nbsp;</li>");
                        ta.bind('click', e => display_items(e.target.text));
                        $("#tags").append(ta);
                    });

                    $("#created").html(data.created);
                    $("#last").html(data.last);
                    $("#filename").html(data.filename);
                    $("#itemout").html(data.content);

                    $('#itemdisplay').show();
                    $('#msg').hide();
                    current_item = itemid;
                    hide_side_show_main();

                } else {
                    alert("Couldn't get info for item " + e.target.id + "\nMessage was: " + data.msg);
                }
            }
        });
    }
    $('.itemlink').click(display_item);

    // Display the items for tag text
    function display_items(t) {
        $.ajax({
            url: "{% url 'core:items' %}",
            data: {
                'tag': t
            },
            dataType: 'json',
            success: function (data) {
                if (data.success) {
                    $("#sidebar-content").empty();
                    JSON.parse(data.items).forEach(idtitle => {
                        var anc = $("<a href='#' class='itemlink' id='" + idtitle[0] + "'>" + idtitle[1] + "</a>");
                        anc.bind('click', display_item);
                        $("#sidebar-content").append(anc);
                        $("#sidebar-content").append($("<br />"));
                        current_tag = t;
                        show_side_hide_main();
                    });
                } else {
                    alert("Couldn't get items for " + t + "\nMessage was: " + data.msg);
                }
            }
        });
    }
    $(".taglink").click(function (e) {
        display_items(e.target.text);
    });
    display_items('Recipes');

    // Delete button
    $("#del-button").click(function () {
        if ( ! current_item ) { return }
        $.ajax({
            url: "{% url 'core:item_delete' %}",
            data: {
                'id': current_item
            },
            dataType: 'json',
            success: function (data) {
                if (data.success) {
                    $('#itemdisplay').hide();
                    display_items(current_tag);
                    current_item = null;
                } else {
                    alert("Couldn't delete " + current_item + "\nMessage was: " + data.msg);
                }
            }
        });
    });

    // Search button clicked when type Enter
    $("#search-lookfor").keypress(function (e) {
        if (e.which == 13) {
            $("#search-button").click();
            return false;
        }
    });
    $("#search-button").click(function () {
        const lookfor = $("#search-lookfor").val()
        if ( ! lookfor ) return;

        $.ajax({
            url: "{% url 'core:search' %}",
            data: {
                'tag': current_tag,
                'lookfor': lookfor
            },
            dataType: 'json',
            success: function (data) {
                if (data.success) {
                    $("#sidebar-content").empty();
                    JSON.parse(data.items).forEach(item => {
                        var anc = $("<a href='#' class='itemlink' id='" + item[0] + "'>" + item[1] + "</a>");
                        anc.bind('click', display_item);
                        $("#sidebar-content").append(anc);
                        $("#sidebar-content").append(item[2] ? ("<br />" + item[2] + "<br />") : "<br />");
                        show_side_hide_main();
                    });
                } else {
                    alert("Couldn't search for " + lookfor + "\nMessage was: " + data.msg);
                }
            }
        });
    });


    let wakeLock = null;

    // Function to request a wake lock
    const requestWakeLock = async () => {
      try {
        wakeLock = await navigator.wakeLock.request('screen');
        console.log('Wake Lock is active');
        
        wakeLock.addEventListener('release', () => {
          console.log('Wake Lock has been released');
        });
      } catch (err) {
        console.error(`Failed to obtain wake lock: ${err}`);
      }
    };

    requestWakeLock();
});

</script>


      
{% endblock %}